blank_issues_enabled: false # Encourage users to use templates
contact_links:
  - name: Project Readme
    url: https://github.com/fderuiter/wedding_website/blob/main/README.md
    about: Please check the README for general info and setup instructions first.
