import { prisma } from '@/lib/prisma';
import { BaseRepository } from './repository';
import { BaseService } from './service';
import { coordinateSchema } from '@/utils/validation';
import { WeddingPartyMemberSchema } from '@/features/wedding-party/schemas';
import { ContentNodeSchema } from '@/features/content/schemas';
import { RegistryItemSchema } from '@/features/registry/schemas';
import { z } from 'zod';

export interface EntityConfig {
  modelName: string;
  entityType: string;
  // declarative custom validation or mapping can be added here
  validateCreate?: (data: any) => string | null;
  validateUpdate?: (data: any) => string | null;
  mapData?: (data: any) => Promise<any> | any;
}

async function handleMediaFields(data: any, idField: string, urlField: string, altField: string, decField: string) {
  let mediaId = data[idField];
  const url = data[urlField];
  const alt = data[altField];
  const dec = data[decField];
  
  if (url || alt !== undefined || dec !== undefined) {
     if (mediaId) {
        await prisma.media.update({
          where: { id: mediaId },
          data: {
             ...(url !== undefined && { url }),
             ...(alt !== undefined && { altText: alt }),
             ...(dec !== undefined && { isDecorative: dec }),
          }
        });
     } else {
        const media = await prisma.media.create({
          data: {
             url: url || '/images/placeholder.png',
             altText: alt || null,
             isDecorative: dec || false,
          }
        });
        mediaId = media.id;
     }
  } else if (!mediaId) {
     const media = await prisma.media.create({
        data: {
           url: '/images/placeholder.png',
           isDecorative: true
        }
     });
     mediaId = media.id;
  }
  
  const mapped = { ...data, [idField]: mediaId };
  delete mapped[urlField];
  delete mapped[altField];
  delete mapped[decField];
  delete mapped.photo;
  delete mapped.image;
  return mapped;
}

async function mapWeddingPartyData(data: any): Promise<any> {
  return await handleMediaFields(data, 'photoId', 'photoUrl', 'photoAlt', 'photoDecorative');
}

function validateCoordinates(data: any): string | null {
  const parsedLat = coordinateSchema.safeParse(data.latitude || 0);
  const parsedLon = coordinateSchema.safeParse(data.longitude || 0);
  if (!parsedLat.success && !parsedLon.success) {
    return 'Invalid coordinate format for latitude and longitude. Must be a numeric value or a placeholder.';
  }
  if (!parsedLat.success) {
    return 'Invalid coordinate format for latitude. Must be a numeric value or a placeholder.';
  }
  if (!parsedLon.success) {
    return 'Invalid coordinate format for longitude. Must be a numeric value or a placeholder.';
  }
  return null;
}

async function mapAttractionData(data: any): Promise<any> {
  const parsedLat = coordinateSchema.safeParse(data.latitude || 0);
  const parsedLon = coordinateSchema.safeParse(data.longitude || 0);
  const mapped = await handleMediaFields(data, 'imageId', 'imageUrl', 'imageAlt', 'imageDecorative');
  return {
    ...mapped,
    latitude: parsedLat.success ? parsedLat.data : 0,
    longitude: parsedLon.success ? parsedLon.data : 0,
  };
}

// Omit fields that are typically generated by the database
const WeddingPartyInputSchema = WeddingPartyMemberSchema.omit({ id: true, createdAt: true, updatedAt: true }).partial({ link: true, photo: true });

function validateWeddingParty(data: any): string | null {
  const result = WeddingPartyInputSchema.safeParse(data);
  if (!result.success) {
    return result.error.issues.map(e => `${e.path.join('.')}: ${e.message}`).join(', ');
  }
  return null;
}

const ContentNodeInputSchema = z.union([
  ContentNodeSchema.options[0].omit({ id: true, createdAt: true, updatedAt: true }),
  ContentNodeSchema.options[1].omit({ id: true, createdAt: true, updatedAt: true }),
  ContentNodeSchema.options[2].omit({ id: true, createdAt: true, updatedAt: true }),
]);

function validateContentNodeUpdate(data: any): string | null {
  const result = ContentNodeInputSchema.safeParse(data);
  if (!result.success) {
    return result.error.issues.map(e => `${e.path.join('.')}: ${e.message}`).join(', ');
  }
  return null;
}

const RegistryItemInputSchema = RegistryItemSchema.omit({ id: true }).partial();

function validateRegistryItem(data: any): string | null {
  const result = RegistryItemInputSchema.safeParse(data);
  if (!result.success) {
    return result.error.issues.map(e => `${e.path.join('.')}: ${e.message}`).join(', ');
  }
  return null;
}

const entityConfigs: Record<string, EntityConfig> = {
  'wedding-party': {
    modelName: 'weddingPartyMember',
    mapData: mapWeddingPartyData,
    entityType: 'WeddingPartyMember',
    validateCreate: validateWeddingParty,
    validateUpdate: validateWeddingParty,
  },
  'attractions': {
    modelName: 'attraction',
    entityType: 'Attraction',
    validateCreate: validateCoordinates,
    validateUpdate: validateCoordinates,
    mapData: mapAttractionData,
  },
  'registry-items': {
    modelName: 'registryItem',
    entityType: 'RegistryItem',
    validateCreate: validateRegistryItem,
    validateUpdate: validateRegistryItem,
  },
  'content-nodes': {
    modelName: 'contentNode',
    entityType: 'ContentNode',
    validateUpdate: validateContentNodeUpdate,
  }
};

/**
 * Retrieve the service and configuration for a registered admin entity key.
 *
 * @param entityKey - The registry key identifying the entity (e.g., 'wedding-party', 'attractions', 'registry-items', 'content-nodes')
 * @returns An object containing `service` (a BaseService instance) and `config` (the EntityConfig) for the given key, or `null` if the key is not registered
 */
export function getEntityService(entityKey: string) {
  const config = entityConfigs[entityKey];
  if (!config) return null;

  const repo = new BaseRepository(config.modelName);
  return {
    service: new BaseService(repo, config.entityType),
    config
  };
}
