import fs from 'fs';
import path from 'path';
import { z } from 'zod';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Generate Configuration Markdown from Schema
import { AppConfigSchema } from '../src/features/content/schemas.ts';

function getZodType(schema: any): string {
  const t = schema.type || schema._def?.typeName;
  if (t === 'string' || t === 'ZodString') return 'string';
  if (t === 'number' || t === 'ZodNumber') return 'number';
  if (t === 'boolean' || t === 'ZodBoolean') return 'boolean';
  if (t === 'date' || t === 'ZodDate') return 'date';
  if (t === 'union' || t === 'ZodUnion') return schema.def?.options?.map(getZodType).join(' | ') || schema._def?.options?.map(getZodType).join(' | ');
  if (t === 'array' || t === 'ZodArray') return getZodType(schema.def?.type || schema._def?.type) + '[]';
  if (t === 'pipeline' || t === 'ZodPipeline') return getZodType(schema.def?.out || schema._def?.out);
  if (t === 'object' || t === 'ZodObject') return 'object';
  if (t === 'any' || t === 'ZodAny') return 'any';
  return t || 'unknown';
}

function generateConfigTable() {
  const shape = AppConfigSchema.shape;
  let markdown = '| Field | Type | Description |\n|---|---|---|\n';
  
  for (const [key, value] of Object.entries(shape)) {
    let type = getZodType(value);
    markdown += `| \`${key}\` | \`${type}\` | Configuration field for ${key} |\n`;
  }
  
  return markdown;
}

// 2. Generate Routing Structure
function getDirectories(srcPath: string, rootPath: string = ''): string[] {
  let routes: string[] = [];
  const entries = fs.readdirSync(srcPath, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory() && !entry.name.includes('__tests__') && !entry.name.includes('components')) {
      const fullPath = path.join(srcPath, entry.name);
      const relativePath = path.join(rootPath, entry.name);
      routes.push(relativePath);
      routes.push(...getDirectories(fullPath, relativePath));
    }
  }
  return routes;
}

function generateRoutesDiagram() {
  const srcAppPath = path.join(__dirname, '../src/app');
  const dirs = getDirectories(srcAppPath);
  
  let treeMarkdown = '```mermaid\nflowchart LR\n';
  treeMarkdown += '    App["src/app"]\n';
  
  for (const dir of dirs) {
    const parts = dir.split(path.sep);
    let parent = 'App';
    for (let i = 0; i < parts.length; i++) {
      const current = 'node_' + parts.slice(0, i + 1).join('_').replace(/\[|\]|-/g, '');
      const currentName = parts[i];
      if (!treeMarkdown.includes(` ${current}["${currentName}"]`)) {
        treeMarkdown += `    ${current}["${currentName}"]\n`;
      }
      if (!treeMarkdown.includes(`${parent} --> ${current}`)) {
        treeMarkdown += `    ${parent} --> ${current}\n`;
      }
      parent = current;
    }
  }
  treeMarkdown += '```\n';
  return treeMarkdown;
}

// 3. Generate Environment Specs
function generateEnvSpecs() {
  const pkgPath = path.join(__dirname, '../package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  
  // We specify Node 22 as per requirements
  const nodeVersion = '22.x'; 
  
  return `- **Node.js**: v${nodeVersion}
- **Next.js**: ${pkg.dependencies.next}
- **React**: ${pkg.dependencies.react}
- **Prisma**: ${pkg.dependencies['@prisma/client'] || pkg.dependencies['@prisma/config'] || pkg.devDependencies['@prisma/client']}
- **Zod**: ${pkg.dependencies.zod}`;
}

// 4. Update ARCHITECTURE.md
function updateArchitectureMd() {
  const filePath = path.join(__dirname, '../ARCHITECTURE.md');
  let content = fs.readFileSync(filePath, 'utf8');

  // Replace Env
  const envRegex = /<!-- BEGIN AUTOGENERATED ENV -->[\s\S]*<!-- END AUTOGENERATED ENV -->/;
  content = content.replace(envRegex, `<!-- BEGIN AUTOGENERATED ENV -->\n${generateEnvSpecs()}\n<!-- END AUTOGENERATED ENV -->`);

  // Replace Routes
  const routesRegex = /<!-- BEGIN AUTOGENERATED ROUTES -->[\s\S]*<!-- END AUTOGENERATED ROUTES -->/;
  content = content.replace(routesRegex, `<!-- BEGIN AUTOGENERATED ROUTES -->\n${generateRoutesDiagram()}\n<!-- END AUTOGENERATED ROUTES -->`);

  // Replace Config
  const configRegex = /<!-- BEGIN AUTOGENERATED CONFIG -->[\s\S]*<!-- END AUTOGENERATED CONFIG -->/;
  content = content.replace(configRegex, `<!-- BEGIN AUTOGENERATED CONFIG -->\n${generateConfigTable()}\n<!-- END AUTOGENERATED CONFIG -->`);

  fs.writeFileSync(filePath, content);
  console.log('Successfully updated ARCHITECTURE.md');
}

updateArchitectureMd();
